// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Return web options for web platform
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    appId: '1:184873604977:android:5283de19efef10c11448d0',
    messagingSenderId: '184873604977',
    projectId: 'b2b-store-9f4f1',
    storageBucket: 'b2b-store-9f4f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJH6zpYEpt4Nq5E8hjlvX87iTjlI4pYIA',
    appId: '1:184873604977:ios:895af177e84477c91448d0',
    messagingSenderId: '184873604977',
    projectId: 'b2b-store-9f4f1',
    storageBucket: 'b2b-store-9f4f1.appspot.com',
    iosBundleId: 'com.example.b2b',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAbJznCX0fnxI0JwLff26Uc3adEZJyY84o",
    authDomain: "b2b-store-9f4f1.firebaseapp.com",
    projectId: "b2b-store-9f4f1",
    storageBucket: "b2b-store-9f4f1.appspot.com",
    messagingSenderId: "184873604977",
    appId: "1:184873604977:web:06bb255fe0b6ff191448d0",
  );
}
